/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.12.0+p57-g7d464570
 *
 * Project: 'Blinky.Debug+PIC32CM6408PL10048' 
 * Target:  'Debug+PIC32CM6408PL10048' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "pic32c.h"

/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::CMSIS:RTOS2:Keil RTX5&Library@5.9.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
/* Microchip::CMSIS Driver:GPIO&Release@1.0.0 */
#include "Driver_GPIO.h"
/* Microchip::CMSIS Driver:USART:USART1&Release@1.0.0 */
#define RTE_Driver_USART_1
#include "Config_USART1.h"
#include "Driver_SERCOM_USART.h"
/* Microchip::MCHP-PLIB:GCLK&Release@1.0.0 */
#include "plib_gclk.h"
/* Microchip::MCHP-PLIB:MCLK&Release@1.0.0 */
#include "plib_mclk.h"
/* Microchip::MCHP-PLIB:OSCCTRL&Release@1.0.0 */
#include "plib_oscctrl.h"
/* Microchip::MCHP-PLIB:PORT&Release@1.0.0 */
#include "plib_port.h"
/* Microchip::MCHP-PLIB:SERCOM:SERCOM_USART1&Release@1.0.0 */
#include "plib_sercom1_usart.h"
#include "plib_sercom_usart_common.h"
#include "plib_sercom_common.h"
/* Microchip::MCHP-PLIB:System Interrupt&Release@1.0.0 */
#include "system_interrupt.h"


#endif /* RTE_COMPONENTS_H */
